export const PKG_PREFIX = '@icee-ui'
export const PKG_NAME = 'icee-ui'
export const PKG_CAMELCASE_NAME = 'IceeUI'
export const PKG_CAMELCASE_LOCAL_NAME = 'IceeUILocale'
export const PKG_BRAND_NAME = 'Icee UI'
